### PR TITLE
Fb add capabilities multi vane and fan speed support

### PR DESCRIPTION
**Pull request by florianbrede-ayet**
I've added a number of new features:
- Detect & store capabilitites (after initial installation, the esp32 will reboot automatically one time after receiving 0xC9 to send the correct climate traits)
- Disable / hide unsupported climate and general entitites
- Support for up to 4 vanes
- Slow fan mode support (displayed as "QUIET" in HA)
- Exposed installer fan speed configuration to HA entities for easier fine-tuning (0-255 - but I'd be cautious at values over 60, it's like a jet taking off)
- Small improvements in procotol.md / fixed the vertical / horizontal swing capability flags

This is how it looks like:
image
image
image
image

### CODE REVIEW

**Comment by JanM321** [comment]
Thanks for doing this. Regarding the 4 vanes detection: from what I remember, I think that's covered by the two upper bits of byte 5, where it's something like 0 = 4 vanes, 1 = 1 vane, 2 = 2 vanes, 3 = ?

I'll see if I can figure out more about these bits that are set in your C9 messages by sending them to the PREMTB001 controller and seeing if it behaves differently. I want to collect as much information as possible about the protocol while I still have the controller hooked up to my laptop.

Do the 4 vanes also support 6 different positions? I was wondering if there's a difference there.

**Comment by drbugfinder** [comment]
> * Slow fan mode support (displayed as "QUIET" in HA)

According to the screenshot, I guess your QUIET mode is for the indoor unit. My S12ET units have no quiet mode for the indoor units, but they support a quiet mode for the outside unit.

**Comment by JanM321** [comment]
I looked a bit more into the capabilities message. I updated protocol.md with the "elevation grill" flag / settings.

The other unknown bits I don't see what they're for. The number of vertical vanes is determined by the upper bits of byte 5: 0 = 4 vanes, 1 = 1 vane, 2 or 3 = 2 vanes. So for this I think we care just about those two bits + the "vertical vane control" bit.

**Review by JanM321 — COMMENTED** [review]
My units don't support the fan speed installer setting. Can you add a capability flag for the "supports ESP value installer setting" bit and use it to disable these settings? After that I can test this version with my units.

Also `FAN_LOW_MEDIUM` is bit 0x8 and `FAN_MEDIUM_HIGH` is bit 0x10.

**Comment by JanM321** [comment]
Actually I can just change this myself. I'm testing this version now.

**Comment by florianbrede-ayet** [comment]
> My units don't support the fan speed installer setting. Can you add a capability flag for the "supports ESP value installer setting" bit and use it to disable these settings? After that I can test this version with my units.

Bummer, I messed up ESP with static pressure and thought it would work regardless of support - but actually my Artcool Gallery has the ESP flag set.
I will add a check for that and hide all the related entities if unsupported.

> Also `FAN_LOW_MEDIUM` is bit 0x8 and `FAN_MEDIUM_HIGH` is bit 0x10.

Thanks, will fix that.
I don't have a unit with support for those modes and I don't think I can expose them in HA, because the climate entity from esphome is limited to the modes available in the enum.



> > * Slow fan mode support (displayed as "QUIET" in HA)
> According to the screenshot, I guess your QUIET mode is for the indoor unit. My S12ET units have no quiet mode for the indoor units, but they support a quiet mode for the outside unit.

You're right, the "SLOW" indoor fan mode is shown as "QUIET" in Home Assistant. That's again a limitation of esphome and their climate entity.

So it's not the "Silent Mode" supported by some single split ODU.
That could possibly be added as well since it's available in `0xAE/0xCE`, but I have no way of testing it. 
Multi-split ODUs only have a power limit jumper on their PCB.

**Comment by florianbrede-ayet** [comment]
> Actually I can just change this myself. I'm testing this version now.

Ok great, let me know if you find anything I should change.

**Comment by JanM321** [comment]
It works great! I still have the same settings available :)

(I just realized I should probably add a switch for "auto clean" at some point. That should be easy to add now and will be useful in the summer.)

**Comment by JanM321** [comment]
@florianbrede-ayet just curious, does your Artcool Gallery unit support all vane positions? If I remember correctly from yesterday, if I send its C9 message to the LG PREMTB001, I could only enable/disable vertical swing but nothing else because the "vane control" bit isn't set.

It's possible the unit or controller is just too pessimistic. My units report not supporting half degrees Celsius for example even though with the custom controller it works fine.

**Comment by florianbrede-ayet** [comment]
@JanM321 no it doesn't, at least not in heating mode and I doubt that it works in cooling.

Side note: Interestingly, ThinQ does not allow swing in heating mode although that function actually works when requested.

**Comment by JanM321** [comment]
> Guys I do have 2011 LG Therma V air-water heat pump - can do some tests for you as I'd love to be able integrate mine with HA too :) - do I need to do some LIN sniffing or just try your code first?

Which LG controllers are compatible with it? That might tell us something. 

Here's a project that suggests the hardware might be similar but the protocol is different: https://github.com/cribskip/esp8266_lgawhp

**Comment by martiinezz** [comment]
I have CN_REMO on the PCB - the controller is old mono LCD based display with rubber buttons. Controller doesn't look like PENKTH000. Looks like this: https://www.elektroda.pl/rtvforum/topic2154274.html so it seems to be PQRCUSA0

**Comment by JanM321** [comment]
> I have CN_REMO on the PCB - the controller is old mono LCD based display with rubber buttons. Controller doesn't look like PENKTH000. Looks like this: https://www.elektroda.pl/rtvforum/topic2154274.html so it seems to be PQRCUSA0 - this is exatly mine: https://wentylacja.com.pl/photo/article/i850x850/pompa-ciepla-w-domu-jednorodzinnym-55148.jpg

You could try it, or figure out a way to sniff the signals from the LG controller. I expect the air-water heat pump to use a different protocol though.

**Pull request merged**
